In [4]:
import torch
import numpy as np

In [15]:
a = torch.as_tensor([1,2,3])
b = torch.as_tensor([3,2,1])

In [16]:
A, B = torch.meshgrid(a, b)

C:\Users\user\anaconda3\envs\dl\lib\site-packages\torch\functional.py:568: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\TensorShape.cpp:2228.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]


In [17]:
A

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])

In [18]:
B

tensor([[3, 2, 1],
        [3, 2, 1],
        [3, 2, 1]])

In [24]:
C = torch.cat([A[...,None], B[...,None]], dim=-1)

In [25]:
C.view(-1, 2)

tensor([[1, 3],
        [1, 2],
        [1, 1],
        [2, 3],
        [2, 2],
        [2, 1],
        [3, 3],
        [3, 2],
        [3, 1]])

In [29]:
np.array([True])*np.array([True])

array([ True])